//go:build ignore

// Command gen_slacknames downloads the iamcal/emoji-data dataset — the
// same canonical standard-emoji table Slack bundles into its web client
// — and generates slacknames_gen.go.
//
// Slack's reactions.add API validates the emoji `name` against this set
// (plus per-workspace custom emoji). The third-party kyokomi/emoji map
// that drives our picker carries extra CLDR-style aliases (e.g.
// "thumbs_up", "OK_hand", "check_mark") that Slack rejects as
// invalid_name. This table lets us canonicalize any picked shortcode to
// the name Slack actually accepts (e.g. "+1"), keyed both by alias and
// by Unicode codepoint sequence.
//
// Run with:
//
//	go generate ./internal/emoji/...
//
// Provenance: https://github.com/iamcal/emoji-data (emoji.json, pinned tag).
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"io"
	"log"
	"net/http"
	"os"
	"sort"
	"strconv"
	"strings"
)

// Pinned to a tagged release so `go generate` is reproducible. Bump
// deliberately when refreshing the emoji set.
const sourceURL = "https://raw.githubusercontent.com/iamcal/emoji-data/v16.0.0/emoji.json"

type entry struct {
	Unified    string   `json:"unified"`
	ShortName  string   `json:"short_name"`
	ShortNames []string `json:"short_names"`
	SortOrder  int      `json:"sort_order"`
}

// unifiedToGlyph converts an iamcal "unified" codepoint string (uppercase
// hex, dash-joined, e.g. "1F44D" or "2764-FE0F") into the rendered glyph.
// Returns "" if any segment fails to parse. The resulting rune sequence
// is byte-for-byte identical to kyokomi/emoji's CodeMap glyphs (verified
// across simple, VS16, keycap, ZWJ-family, and flag emoji).
func unifiedToGlyph(unified string) string {
	parts := strings.Split(unified, "-")
	rs := make([]rune, 0, len(parts))
	for _, p := range parts {
		n, err := strconv.ParseInt(p, 16, 32)
		if err != nil {
			return ""
		}
		rs = append(rs, rune(n))
	}
	return string(rs)
}

func main() {
	resp, err := http.Get(sourceURL)
	if err != nil {
		log.Fatalf("fetching %s: %v", sourceURL, err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		log.Fatalf("fetching %s: status %d", sourceURL, resp.StatusCode)
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		log.Fatalf("reading body: %v", err)
	}

	var entries []entry
	if err := json.Unmarshal(body, &entries); err != nil {
		log.Fatalf("decoding emoji.json: %v", err)
	}

	// Deterministic order: iamcal sort_order.
	sort.Slice(entries, func(i, j int) bool { return entries[i].SortOrder < entries[j].SortOrder })

	nameToCanonical := map[string]string{} // alias -> canonical short_name
	codeMap := map[string]string{}         // ":name:" -> glyph (all aliases)

	for _, e := range entries {
		if e.ShortName == "" {
			continue
		}
		glyph := unifiedToGlyph(e.Unified)
		for _, n := range e.ShortNames {
			if _, ok := nameToCanonical[n]; !ok {
				nameToCanonical[n] = e.ShortName
			}
			if glyph != "" {
				if key := ":" + n + ":"; codeMap[key] == "" {
					codeMap[key] = glyph
				}
			}
		}
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by gen_slacknames.go from iamcal/emoji-data. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package emoji\n\n")
	fmt.Fprintf(&buf, "// slackNameToCanonical maps every Slack emoji alias short_name to its\n")
	fmt.Fprintf(&buf, "// canonical short_name (the name Slack's reactions.add expects).\n")
	writeMap(&buf, "slackNameToCanonical", nameToCanonical)
	fmt.Fprintf(&buf, "\n// slackCodeMap maps every Slack emoji shortcode (\":name:\", all aliases)\n")
	fmt.Fprintf(&buf, "// to its rendered Unicode glyph, derived from iamcal codepoints. This is\n")
	fmt.Fprintf(&buf, "// mmk's standard-emoji source, replacing kyokomi/emoji's CodeMap.\n")
	writeMap(&buf, "slackCodeMap", codeMap)

	src, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("gofmt output: %v", err)
	}
	if err := os.WriteFile("slacknames_gen.go", src, 0o644); err != nil {
		log.Fatalf("writing slacknames_gen.go: %v", err)
	}

	log.Printf("wrote slacknames_gen.go: %d names, %d shortcodes", len(nameToCanonical), len(codeMap))
}

func writeMap(buf *bytes.Buffer, name string, m map[string]string) {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	fmt.Fprintf(buf, "var %s = map[string]string{\n", name)
	for _, k := range keys {
		fmt.Fprintf(buf, "\t%q: %q,\n", k, m[k])
	}
	fmt.Fprintf(buf, "}\n")
}
